dbuser=SIMBA
dbpass=simba
dbport=1521
dbhost=172.16.210.103
dbsid=UATDB
mailhost=172.16.100.2
tlsenable=true
authenable=false
mailport=25
mailuser=operations@vicbank.com
mailpass=Technol
subject=DORMANCY ALERT
body=Dear Client\n\nRE:       DORMANCY ALERT\n______________________________________\n\nWith reference to the above subject, this is to inform you that your account will become dormant in the next 30 days.\n\nTo keep the account active, please visit the nearest VCB branch and transact into the account, failure to which, the Bank will be unable to honour any transactions into the account.\n\nAccording to the Unclaimed Financial Assets Act we are required to surrender dormant account balances for five years and over to the Unclaimed Financial Asset Authority annually , therefore kindly activate your account and transact as soon as possible.\n\n Thank you for the anticipated response.\n\nYours faithfully\nVICTORIA COMMERCIAL BANK LIMITED\n\n\n
body1=Dear Client\n\nRE:       DORMANT ACCOUNT ACTIVATION\n_________________________________________\n\nYour account has defaulted to dormant status , please find attached activation form to activate the dormant account.\n\nKindly fill and sign the form as per the account mandate.  The duly signed form can be returned to any VCB Branch or forwarded to the email address operations@vicbank.com.\n\nThank you in advance\n\n\n
subject1=DORMANT ACCOUNT ACTIVATION
attachmentloc=/home/finadm/VAS/dormantAdvice/
formname=DORMANT ACCOUNT REACTIVATION FORM NEW.pdf
tdbody=Your Term deposit  account is maturing in next 15 days.Visit your nearest branch for further directions.
