server.port=5600



# =========================================
# ACCOUNTS ABOUT TO GO DORMANT
# =========================================
db.query.beforeDormant=select * from SIMBA.ACCOUNTTOBEDORMARNT30

# =========================================
# ACCOUNTS ALREADY DORMANT
# =========================================
db.query.alreadyDormant=select * from SIMBA.dormantaccounts
db.query.monthlyReminder=select * from SIMBA.dormantaccounts30dayreminder

enc.key= VcbKey0123456789
enc.initVector= VcbInitVector012

##Oracle Database Credentials
db.class= mmR/m2BcaZWL+kTu86/9mlWmb9E27fsv3QnWKjkWIx4=
db.ip= CGxr1GoPVFJikXm0OGs8mQ==
db.port= ZWUMLtiLJf0orh1JZA7NGg==
db.database= 2HLR3+xRrSXFxOxkSS4fEA==
#db.database=g76reD/WRg8PiUffOpFtCg==
db.username= +J9A3QabNG8ckUqPt0oP/Q==
db.password= MYQJVb6IXoqWd5MCi1NyBg==

##Oracle EMTECH Database Credentials
#db.class= mmR/m2BcaZWL+kTu86/9mlWmb9E27fsv3QnWKjkWIx4=
#db.ip= 9Kq89HX1UjiiHMJLK//emA==
#db.port= ZWUMLtiLJf0orh1JZA7NGg==
#db.database= Y60tpFpra9AsNi/lpikibg==
#db.username= +J9A3QabNG8ckUqPt0oP/Q==
#db.password= MYQJVb6IXoqWd5MCi1NyBg==


spring.mail.host=172.16.100.2
spring.mail.port=25
spring.mail.username=victoria@vicbank.com
spring.mail.password= #Vicbank1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false



#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
##spring.mail.username=lewisbrat650@gmail.com
##spring.mail.password=mlzi fyzz ewxh hhyb
#spring.mail.username=lewiskipkemoi765@gmail.com
#spring.mail.password=yzvj hzze mrom gbcu
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000