server.port=5600



# =========================================
# ACCOUNTS ABOUT TO GO DORMANT
# =========================================
db.query.beforeDormant=SELECT EMAIL, ACCOUNT_NUMBER, ACCOUNT_NAME \
FROM VCB_ACCOUNTS_TO_GO_DORMANT \
WHERE EMAIL IS NOT NULL

# =========================================
# ACCOUNTS ALREADY DORMANT
# =========================================
db.query.alreadyDormant=SELECT EMAIL, ACCOUNT_NUMBER, ACCOUNT_NAME \
FROM VCB_DORMANT_ACCOUNTS \
WHERE EMAIL IS NOT NULL


##Oracle Database Credentials
db.class= mmR/m2BcaZWL+kTu86/9mlWmb9E27fsv3QnWKjkWIx4=
db.ip= CGxr1GoPVFJikXm0OGs8mQ==
db.port= ZWUMLtiLJf0orh1JZA7NGg==
#db.database= +x+S2es7uUIjGZnjDQN8Ww==
db.database=g76reD/WRg8PiUffOpFtCg==
db.username= +J9A3QabNG8ckUqPt0oP/Q==
db.password= MYQJVb6IXoqWd5MCi1NyBg==

##Oracle EMTECH Database Credentials
#db.class= mmR/m2BcaZWL+kTu86/9mlWmb9E27fsv3QnWKjkWIx4=
#db.ip= 9Kq89HX1UjiiHMJLK//emA==
#db.port= ZWUMLtiLJf0orh1JZA7NGg==
#db.database= Y60tpFpra9AsNi/lpikibg==
#db.username= +J9A3QabNG8ckUqPt0oP/Q==
#db.password= MYQJVb6IXoqWd5MCi1NyBg==


spring.mail.host=172.16.100.2
spring.mail.port=25
spring.mail.username=victoria@vicbank.com
spring.mail.password= #Vicbank1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false